import os, json, base64
import xml.etree.ElementTree as ET

def add_or_update_string(root, name, value):
    for elem in root.findall('string'):
        if elem.get('name') == name:
            elem.text = value
            return
    new_elem = ET.Element('string', name=name)
    new_elem.text = value
    root.append(new_elem)

def patch_file(filepath, updates):
    if not os.path.exists(filepath):
        print(f'Skipping {filepath}')
        return
    tree = ET.parse(filepath)
    root = tree.getroot()
    for k, v in updates.items():
        add_or_update_string(root, k, v)
    tree.write(filepath, encoding='utf-8', xml_declaration=True)
    print(f'Patched {filepath}')

payload = b'ewogICJhcHAvc3JjL21haW4vcmVzL3ZhbHVlcy9zdHJpbmdzLnhtbCI6IHsKICAgICJldmVudF9zYWZldHlfbm90ZSI6ICJBbHdheXMgY2hlY2sgeW91ciBUb2RheSBWaWV3IGluIFBva8OpbW9uIEdPIHRvIGJlIGFic29sdXRlbHkgc3VyZSB0aGUgZXZlbnQgaXMgYWN0aXZlIGJlZm9yZSB0cmFuc2ZlcnJpbmcuIiwKICAgICJldmVudF9jb250ZXh0X2Rpc2NsYWltZXIiOiAiVGhpcyBpcyBhIG1hbnVhbCBndWlkZS4gUG9rZVF1ZXJ5IGRvZXNuJ3QgY29ubmVjdCB0byB5b3VyIGdhbWUsIHNvIGl0IGNhbid0IGtub3cgZm9yIHN1cmUgd2hhdCdzIGFjdGl2ZS4gQWx3YXlzIGRvdWJsZS1jaGVjayBpbi1nYW1lISIKICB9LAogICJhcHAvc3JjL21haW4vcmVzL3ZhbHVlcy10ci9zdHJpbmdzLnhtbCI6IHsKICAgICJldmVudF9zYWZldHlfbm90ZSI6ICJUcmFuc2ZlciB5YXBtYWRhbiDDtm5jZSBldGtpbmxpxJ9pbiBnZXLDp2VrdGVuIGJhxZ9sYWTEscSfxLFuZGFuIGVtaW4gb2xtYWsgacOnaW4gUG9rw6ltb24gR08gacOnaW5kZWtpIEJ1Z8O8biAoVG9kYXkpIHNla21lc2luaSBtdXRsYWthIGtvbnRyb2wgZXQuIiwKICAgICJldmVudF9jb250ZXh0X2Rpc2NsYWltZXIiOiAiQnUgcmVoYmVyIGVsbGUgZ8O8bmNlbGxlbmlyLiBQb2tlUXVlcnkgb3l1bmEgYmHEn2xhbm1hZMSxxJ/EsSBpw6dpbiBha3RpZiBvbGFubGFyxLEga2VzaW4gb2xhcmFrIGJpbGVtZXouIEhlciB6YW1hbiBveXVuIGnDp2luZGVuIGtvbnRyb2wgZXQhIgogIH0sCiAgImFwcC9zcmMvbWFpbi9yZXMvdmFsdWVzLWRlL3N0cmluZ3MueG1sIjogewogICAgImV2ZW50X3NhZmV0eV9ub3RlIjogIsOcYmVycHLDvGZlIGltbWVyIGRlaW5lIEhldXRlLUFuc2ljaHQgaW4gUG9rw6ltb24gR08sIHVtIHNpY2hlcnp1c3RlbGxlbiwgZGFzcyBkYXMgRXZlbnQgYWt0aXYgaXN0LCBiZXZvciBkdSB2ZXJzY2hpY2tzdC4iLAogICAgImV2ZW50X2NvbnRleHRfZGlzY2xhaW1lciI6ICJEaWVzIGlzdCBlaW4gbWFudWVsbGVyIEd1aWRlLiBQb2tlUXVlcnkgdmVyYmluZGV0IHNpY2ggbmljaHQgbWl0IGRlbSBTcGllbCB1bmQgd2Vpw58gbmljaHQgc2ljaGVyLCB3YXMgYWt0aXYgaXN0LiDDnGJlcnByw7xmZSBlcyBpbW1lciBpbSBTcGllbCEiCiAgfSwKICAiYXBwL3NyYy9tYWluL3Jlcy92YWx1ZXMtZXMvc3RyaW5ncy54bWwiOiB7CiAgICAiZXZlbnRfc2FmZXR5X25vdGUiOiAiUmV2aXNhIHNpZW1wcmUgbGEgdmlzdGEgSG95IGVuIFBva8OpbW9uIEdPIHBhcmEgZXN0YXIgYWJzb2x1dGFtZW50ZSBzZWd1cm8gZGUgcXVlIGVsIGV2ZW50byBlc3TDoSBhY3Rpdm8gYW50ZXMgZGUgdHJhbnNmZXJpci4iLAogICAgImV2ZW50X2NvbnRleHRfZGlzY2xhaW1lciI6ICJFc3RhIGVzIHVuYSBndcOtYSBtYW51YWwuIFBva2VRdWVyeSBubyBzZSBjb25lY3RhIGEgdHUganVlZ28sIGFzw60gcXVlIG5vIHB1ZWRlIHNhYmVyIGNvbiBzZWd1cmlkYWQgcXXDqSBlc3TDoSBhY3Rpdm8uIMKhQ29tcHJ1w6liYWxvIHNpZW1wcmUgZW4gZWwganVlZ28hIgogIH0sCiAgImFwcC9zcmMvbWFpbi9yZXMvdmFsdWVzLWZyL3N0cmluZ3MueG1sIjogewogICAgImV2ZW50X3NhZmV0eV9ub3RlIjogIlbDqXJpZmlleiB0b3Vqb3VycyB2b3RyZSB2dWUgQXVqb3VyZCdodWkgZGFucyBQb2vDqW1vbiBHTyBwb3VyIMOqdHJlIGFic29sdW1lbnQgc8O7ciBxdWUgbCfDqXbDqW5lbWVudCBlc3QgYWN0aWYgYXZhbnQgZGUgdHJhbnNmw6lyZXIuIiwKICAgICJldmVudF9jb250ZXh0X2Rpc2NsYWltZXIiOiAiQ2VjaSBlc3QgdW4gZ3VpZGUgbWFudWVsLiBQb2tlUXVlcnkgbmUgc2UgY29ubmVjdGUgcGFzIMOgIHZvdHJlIGpldSwgZG9uYyBpbCBuZSBwZXV0IHBhcyBzYXZvaXIgYXZlYyBjZXJ0aXR1ZGUgY2UgcXVpIGVzdCBhY3RpZi4gVsOpcmlmaWV6IHRvdWpvdXJzIGRhbnMgbGUgamV1ICEiCiAgfSwKICAiYXBwL3NyYy9tYWluL3Jlcy92YWx1ZXMtaXQvc3RyaW5ncy54bWwiOiB7CiAgICAiZXZlbnRfc2FmZXR5X25vdGUiOiAiQ29udHJvbGxhIHNlbXByZSBsYSBzY2hlZGEgT2dnaSBpbiBQb2vDqW1vbiBHTyBwZXIgZXNzZXJlIGFzc29sdXRhbWVudGUgc2ljdXJvIGNoZSBsJ2V2ZW50byBzaWEgYXR0aXZvIHByaW1hIGRpIHRyYXNmZXJpcmUuIiwKICAgICJldmVudF9jb250ZXh0X2Rpc2NsYWltZXIiOiAiUXVlc3RhIMOoIHVuYSBndWlkYSBtYW51YWxlLiBQb2tlUXVlcnkgbm9uIHNpIGNvbm5ldHRlIGFsIHR1byBnaW9jbywgcXVpbmRpIG5vbiBwdcOyIHNhcGVyZSBjb24gY2VydGV6emEgY29zYSBzaWEgYXR0aXZvLiBDb250cm9sbGEgc2VtcHJlIG5lbCBnaW9jbyEiCiAgfQp9'
data = json.loads(base64.b64decode(payload).decode('utf-8'))
for filepath, updates in data.items():
    patch_file(filepath, updates)
