import os, json, base64
import xml.etree.ElementTree as ET

def add_or_update_string(root, name, value):
    for elem in root.findall('string'):
        if elem.get('name') == name:
            elem.text = value
            return
    new_elem = ET.Element('string', name=name)
    new_elem.text = value
    root.append(new_elem)

def patch_file(filepath, updates):
    if not os.path.exists(filepath):
        print(f'Skipping {filepath}, does not exist.')
        return
    tree = ET.parse(filepath)
    root = tree.getroot()
    for k, v in updates.items():
        add_or_update_string(root, k, v)
    tree.write(filepath, encoding='utf-8', xml_declaration=True)
    print(f'Patched {filepath}')

payload = b'ewogICJhcHAvc3JjL21haW4vcmVzL3ZhbHVlcy9zdHJpbmdzLnhtbCI6IHsKICAgICJzZWFyY2hfYXNzaXN0YW50X2VtcHR5X3N0YXRlX3RpdGxlIjogIldoYXQgY2FuIEkgc2VhcmNoIGZvcj8iLAogICAgInNlYXJjaF9hc3Npc3RhbnRfZW1wdHlfc3RhdGVfZGVzYyI6ICJUcnkgbmF0dXJhbCBsYW5ndWFnZSBsaWtlICdzaGlueSBsZWdlbmRhcnkgcG9rZW1vbicgb3IgJ2h1bmRvIGZvciB1bHRyYSBsZWFndWUnLiBUaGUgYXNzaXN0YW50IHdpbGwgdHJhbnNsYXRlIGl0IGludG8gYSBnYW1lLXJlYWR5IHNlYXJjaCBzdHJpbmcuIgogIH0sCiAgImFwcC9zcmMvbWFpbi9yZXMvdmFsdWVzLXRyL3N0cmluZ3MueG1sIjogewogICAgInNlYXJjaF9hc3Npc3RhbnRfZW1wdHlfc3RhdGVfdGl0bGUiOiAiTmVsZXIgYXJheWFiaWxpcmltPyIsCiAgICAic2VhcmNoX2Fzc2lzdGFudF9lbXB0eV9zdGF0ZV9kZXNjIjogIktlbmRpIGtlbGltZWxlcmlubGUgJ3BhcmxhayBlZnNhbmV2aScgdmV5YSAndWx0cmEgbGlnIGnDp2luIGh1bmRvJyB5YXptYXnEsSBkZW5lLiBBc2lzdGFuIGJ1bnUgb3l1bmEgaGF6xLFyIGJpciBhcmFtYSBrb2R1bmEgw6dldmlyaXIuIgogIH0sCiAgImFwcC9zcmMvbWFpbi9yZXMvdmFsdWVzLWRlL3N0cmluZ3MueG1sIjogewogICAgInNlYXJjaF9hc3Npc3RhbnRfZW1wdHlfc3RhdGVfdGl0bGUiOiAiV2FzIGthbm4gaWNoIHN1Y2hlbj8iLAogICAgInNlYXJjaF9hc3Npc3RhbnRfZW1wdHlfc3RhdGVfZGVzYyI6ICJQcm9iaWVyZSBuYXTDvHJsaWNoZSBTcHJhY2hlIHdpZSAnc2hpbnkgbGVnZW5kw6RyJyBvZGVyICdodW5kbyBmw7xyIGh5cGVybGlnYScuIERlciBBc3Npc3RlbnQgw7xiZXJzZXR6dCBlcyBpbiBlaW5lbiBzcGllbGZlcnRpZ2VuIFN1Y2hiZWdyaWZmLiIKICB9LAogICJhcHAvc3JjL21haW4vcmVzL3ZhbHVlcy1lcy9zdHJpbmdzLnhtbCI6IHsKICAgICJzZWFyY2hfYXNzaXN0YW50X2VtcHR5X3N0YXRlX3RpdGxlIjogIsK/UXXDqSBwdWVkbyBidXNjYXI/IiwKICAgICJzZWFyY2hfYXNzaXN0YW50X2VtcHR5X3N0YXRlX2Rlc2MiOiAiUHJ1ZWJhIGNvbiBsZW5ndWFqZSBuYXR1cmFsIGNvbW8gJ2xlZ2VuZGFyaW8gdmFyaW9jb2xvcicgbyAnaHVuZG8gcGFyYSBsaWdhIHVsdHJhJy4gRWwgYXNpc3RlbnRlIGxvIHRyYWR1Y2lyw6EgZW4gdW5hIGNhZGVuYSBkZSBiw7pzcXVlZGEgcGFyYSBlbCBqdWVnby4iCiAgfSwKICAiYXBwL3NyYy9tYWluL3Jlcy92YWx1ZXMtZnIvc3RyaW5ncy54bWwiOiB7CiAgICAic2VhcmNoX2Fzc2lzdGFudF9lbXB0eV9zdGF0ZV90aXRsZSI6ICJRdWUgcHVpcy1qZSBjaGVyY2hlciA/IiwKICAgICJzZWFyY2hfYXNzaXN0YW50X2VtcHR5X3N0YXRlX2Rlc2MiOiAiRXNzYXlleiBhdmVjIGRlcyBtb3RzIHNpbXBsZXMgY29tbWUgJ2zDqWdlbmRhaXJlIGNocm9tYXRpcXVlJyBvdSAnaHVuZG8gcG91ciBsaWd1ZSBoeXBlcicuIEwnYXNzaXN0YW50IGxlIHRyYWR1aXJhIGVuIHVuZSBjaGHDrm5lIGRlIHJlY2hlcmNoZSBwb3VyIGxlIGpldS4iCiAgfSwKICAiYXBwL3NyYy9tYWluL3Jlcy92YWx1ZXMtaXQvc3RyaW5ncy54bWwiOiB7CiAgICAic2VhcmNoX2Fzc2lzdGFudF9lbXB0eV9zdGF0ZV90aXRsZSI6ICJDb3NhIHBvc3NvIGNlcmNhcmU/IiwKICAgICJzZWFyY2hfYXNzaXN0YW50X2VtcHR5X3N0YXRlX2Rlc2MiOiAiUHJvdmEgY29uIHVuIGxpbmd1YWdnaW8gbmF0dXJhbGUgY29tZSAnbGVnZ2VuZGFyaW8gY3JvbWF0aWNvJyBvICdodW5kbyBwZXIgbGVnYSB1bHRyYScuIEwnYXNzaXN0ZW50ZSBsbyB0cmFkdXJyw6AgaW4gdW5hIHN0cmluZ2EgZGkgcmljZXJjYSBwcm9udGEgcGVyIGlsIGdpb2NvLiIKICB9Cn0='
data = json.loads(base64.b64decode(payload).decode('utf-8'))
for filepath, updates in data.items():
    patch_file(filepath, updates)
